sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - PIP_ACCEL_S3_BUCKET=
  - PIP_ACCEL_S3_BUCKET=pip-accel-test-bucket
install:
  - pip install coveralls --editable "file://${PWD}[s3]"
  - gem install fakes3
script:
  ./.travis.sh
after_success:
  coveralls
